# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmpp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Nima(object):
    def setupUi(self, Nima):
        Nima.setObjectName("Nima")
        Nima.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Nima)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 30, 591, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 30, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(20, 550, 731, 16))
        self.statusLabel.setObjectName("statusLabel")
        Nima.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Nima)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Nima.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Nima)
        self.statusbar.setObjectName("statusbar")
        Nima.setStatusBar(self.statusbar)

        self.retranslateUi(Nima)
        QtCore.QMetaObject.connectSlotsByName(Nima)

    def retranslateUi(self, Nima):
        _translate = QtCore.QCoreApplication.translate
        Nima.setWindowTitle(_translate("Nima", "Nima"))
        self.pushButton.setText(_translate("Nima", "PushButton"))
        self.statusLabel.setText(_translate("Nima", "TextLabel"))
