# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagenavigator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageNavigator(object):
    def setupUi(self, PageNavigator):
        PageNavigator.setObjectName("PageNavigator")
        PageNavigator.resize(518, 25)
        PageNavigator.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(PageNavigator)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.previousPageLabel = QtWidgets.QLabel(PageNavigator)
        self.previousPageLabel.setObjectName("previousPageLabel")
        self.horizontalLayout.addWidget(self.previousPageLabel)
        self.previousSeparate = QtWidgets.QWidget(PageNavigator)
        self.previousSeparate.setMinimumSize(QtCore.QSize(15, 0))
        self.previousSeparate.setBaseSize(QtCore.QSize(15, 0))
        self.previousSeparate.setObjectName("previousSeparate")
        self.horizontalLayout.addWidget(self.previousSeparate)
        self.leftPagesWidget = QtWidgets.QWidget(PageNavigator)
        self.leftPagesWidget.setObjectName("leftPagesWidget")
        self.horizontalLayout.addWidget(self.leftPagesWidget)
        self.leftSeparateLabel = QtWidgets.QLabel(PageNavigator)
        self.leftSeparateLabel.setToolTip("")
        self.leftSeparateLabel.setObjectName("leftSeparateLabel")
        self.horizontalLayout.addWidget(self.leftSeparateLabel)
        self.centerPagesWidget = QtWidgets.QWidget(PageNavigator)
        self.centerPagesWidget.setEnabled(True)
        self.centerPagesWidget.setBaseSize(QtCore.QSize(45, 0))
        self.centerPagesWidget.setObjectName("centerPagesWidget")
        self.horizontalLayout.addWidget(self.centerPagesWidget)
        self.rightSeparateLabel = QtWidgets.QLabel(PageNavigator)
        self.rightSeparateLabel.setToolTip("")
        self.rightSeparateLabel.setObjectName("rightSeparateLabel")
        self.horizontalLayout.addWidget(self.rightSeparateLabel)
        self.rightPagesWidget = QtWidgets.QWidget(PageNavigator)
        self.rightPagesWidget.setObjectName("rightPagesWidget")
        self.horizontalLayout.addWidget(self.rightPagesWidget)
        self.nextSeparate = QtWidgets.QWidget(PageNavigator)
        self.nextSeparate.setMinimumSize(QtCore.QSize(15, 0))
        self.nextSeparate.setBaseSize(QtCore.QSize(15, 0))
        self.nextSeparate.setObjectName("nextSeparate")
        self.horizontalLayout.addWidget(self.nextSeparate)
        self.nextPageLabel = QtWidgets.QLabel(PageNavigator)
        self.nextPageLabel.setObjectName("nextPageLabel")
        self.horizontalLayout.addWidget(self.nextPageLabel)
        self.label = QtWidgets.QLabel(PageNavigator)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pageLineEdit = QtWidgets.QLineEdit(PageNavigator)
        self.pageLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.pageLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pageLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pageLineEdit.setObjectName("pageLineEdit")
        self.horizontalLayout.addWidget(self.pageLineEdit)
        self.label_2 = QtWidgets.QLabel(PageNavigator)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(PageNavigator)
        QtCore.QMetaObject.connectSlotsByName(PageNavigator)

    def retranslateUi(self, PageNavigator):
        _translate = QtCore.QCoreApplication.translate
        PageNavigator.setWindowTitle(_translate("PageNavigator", "Form"))
        self.previousPageLabel.setToolTip(_translate("PageNavigator", "上一页"))
        self.previousPageLabel.setText(_translate("PageNavigator", "<<"))
        self.leftSeparateLabel.setText(_translate("PageNavigator", ".."))
        self.rightSeparateLabel.setText(_translate("PageNavigator", ".."))
        self.nextPageLabel.setToolTip(_translate("PageNavigator", "下一页"))
        self.nextPageLabel.setText(_translate("PageNavigator", ">>"))
        self.label.setText(_translate("PageNavigator", "第"))
        self.label_2.setText(_translate("PageNavigator", "页"))

    def getLeftPagesWidget(self):
        return self.leftPagesWidget